### ISSUE TITLE
contact for reporting security issue

### ISSUE THREAD

**Issue by Duncaen** [cruegge/pam-gnupg#14]
I've found a security issue in pam-gnupg and would like to privately contact you but couldn't find any e-mail address.

**Comment by cruegge** [comment]
Right, I should add that somewhere. My email is mail@cxcs.de. If you want to use gpg, my key is available at https://pgp.mit.edu/pks/lookup?op=get&search=0x42F4C11E11F0CD02, fingerprint `EA41 74A7 9369 5D92 CB93  B1BE 42F4 C11E 11F0 CD02`.

**Comment by Duncaen** [comment]
Thanks for the fast response, I've send you the details, my key is `C4B6 FBA9 8211 F7EF F35D EB73 335C 1D17 EC3D 6E35`.

https://keybase.io/duncaen
https://π.duncano.de/duncan.asc
