### ISSUE TITLE
crond configuration

### ISSUE THREAD

**Issue by tm-st** [cruegge/pam-gnupg#17]
Hi,

Do you have any recommendations on how to configure this in `/etc/pam.d/crond`

I've added the following line to the `/etc/pam.d/crond` file:

`account   sufficient  pam_gnupg.so`

But the gpg key still requires a passphrase when the cron job is run.

I've set `allow-preset-passphrase` and `max-cache-ttl 86400` in `~/.gnupg/gpg-agent.conf` and added the keygrips to `~/.pam-gnupg`

Thanks in advance.

**Comment by cruegge** [comment]
I'm pretty sure that's not possible. All pam_gnupg does is to memorize the typed-in passphrase until the pam session is opened, and then send it to gpg-agent and forget it. Cron never asks for a passphrase. Instead it uses the fact that the daemon runs as root and can simply authenticate as any user it wants.

As long as you're logged in, your cron jobs *should* be able to access your login session's gpg-agent if it's running. I think there might not even be any configuration neccessary, gnupg puts the agent socket in a fixed location by default. If you're logged out, however, there's no way to access your keys.

**Comment by tm-st** [comment]
Thanks for getting back to me. It does work if I add the auth and session configuration to `/etc/pam.d/kde` but my reasons for using cron was a worry about expiration. I was hoping that by configuring it to work with crond, that the passphrase would be passed to pam_gnupg (and therefore the gpg-agent) whenever a cronjob starts.

Thanks again.

**Comment by cruegge** [comment]
If all you want to do is to prevent expiration, you can just choose a very large `max-cache-ttl`, I suppose.

I'll close this issue.
