### ISSUE TITLE
unable to setup

### ISSUE THREAD

**Issue by candreslobor** [cruegge/pam-gnupg#29]
I've follow all the readme instructions but pass keep asking for password every time i prompt it
my setup looks like this:

`/etc/pam.d/system-local-login`
```
#%PAM-1.0

auth      include   system-login
account   include   system-login
password  include   system-login
session   include   system-login

session required pam_env.so

auth     optional  pam_gnupg.so
session  optional  pam_gnupg.so
```

`$HOME/.local/share/gnupg/gpg-agent.conf`
```
allow-preset-passphrase
```

`$HOME/.pam-gnupg`
```
contains the ssb keygrip
```

`$HOME/.pam_enviroment`
```
GNUPGHOME DEFAUL=@{HOME}/.local/share/gnupg
```

What am i doing wrong?

System: Arch Linux
Login: tty

**Comment by cruegge** [comment]
>     GNUPGHOME DEFAUL=@{HOME}/.local/share/gnupg

There's a typo, it should be`DEFAULT`.

You should also add the`store-only` option to the`auth`line. Otherwise, the password is already sent during authentication, where `.pam_environment` is not used.

**Comment by candreslobor** [comment]
Thanks for the quick response, i fixed the typo and i've add `store-only` at the of the `auth` line. The problem persist

**Comment by cruegge** [comment]
Is the line `session required pam_env.so` in `system-local-login` really needed? It should already be in the included `system-login`. If it is really needed in this place, can you try adding the `user_readenv=1` option? Without that, your `.pam_environment` will be ignored.

**Comment by candreslobor** [comment]
somehow when i make the file to look like this:
```
#%PAM-1.0

auth      include   system-login
account   include   system-login
password  include   system-login
session   include   system-login

user_readenv=1

auth     optional  pam_gnupg.so store-only
session  optional  pam_gnupg.so
```

i'm unable to login with my user or the root user

**Comment by cruegge** [comment]
I meant adding the option to the existing line:

    session required pam_env.so user_readenv=1

**Comment by candreslobor** [comment]
now it looks like this:
```
#%PAM-1.0

auth      include   system-login
account   include   system-login
password  include   system-login
session   include   system-login

auth 	optional pam_gnupg.so store-only
session optional pam_gnupg.so
session required pam_env.so user_readenv=1
```
but pass keep asking me for password

**Comment by candreslobor** [comment]
I fix the issue by moving the gnupg folder to my $HOME directory
