### ISSUE TITLE
question: i3lock clear password cache

### ISSUE THREAD

**Issue by shibumi** [cruegge/pam-gnupg#3]
Hey,
Sorry I know this is not project related, but I am curios how you clear your password cache when you invoke i3lock. You have mentioned this in your `README`:

`so I can clear the password cache when locking the screen, and have my keys unlocked automatically afterwards`

**Comment by cruegge** [comment]
I'm using [xss-lock](https://bitbucket.org/raymonad/xss-lock) to launch i3lock. I run it from my `.xinitrc` like

    xss-lock lock-session.sh &

where `lock-session.sh` is a script that contains

    echo reloadagent | gpg-connect-agent
    exec i3lock --nofork

**Comment by shibumi** [comment]
ah ok. Thats exactly what I have expected. I thought you have something special :D 
Thanks for the fast answer. closing this for keeping your issues clean :)
