### ISSUE TITLE
Could store-only be detected from PAM_TYPE?

### ISSUE THREAD

**Issue by OJFord** [cruegge/pam-gnupg#32]
Just a thought, if the only reason to use it is on `auth`, and it's always needed on `auth`, that instead of needing to be specified it could be inferred?

**Comment by cruegge** [comment]
Unfortunately no, because it's not always needed on `auth`, only for pam services that open sessions. For screen lockers, it must not be specified, because they never do anything but authentication, and so the passphrase needs to be sent right away.
