### ISSUE TITLE
Moving gpg folder with GNUPGHOME

### ISSUE THREAD

**Issue by GandaG** [cruegge/pam-gnupg#4]
Newbie to gpg here, sorry if it's obvious.

I moved the gpg folder to `~/.config/gnupg` with `GNUPGHOME` in `~/.bash_profile`. pam-gnupg was working previously, followed all your instructions in the readme.

Now gpg is no longer unlocked at login and a `~/.gnupg/private-keys-v1.d` empty folder is created. Any help is appreciated, thanks!

**Comment by cruegge** [comment]
Setting the environment variable in `.bash_profile` is probably too late; the pam stack runs before bash is initialized. You might try setting it through `pam_env(8)` by adding

    GNUPGHOME DEFAULT=@{HOME}/.config/gnupg

to your `~/.pam_environment` (see `pam_env.conf(5)` for details). Also, make sure that `pam_env.so` is run before `pam_gnupg.so` in your pam stack.

**Comment by GandaG** [comment]
Added `~/.pam_environment` and `/etc/pam.d/system-local-login` includes `system-login` at the top which has `session    required   pam_env.so` at the end so I'm guessing it's above `pam_gnupg.so`.

The empty folder is no longer created but it still requests the passphrase when using pass the first time.

**Comment by cruegge** [comment]
Looks like there are some additional steps needed to actually use the environment that pam_env sets. I just pushed a possible fix. Can you test?

**Comment by GandaG** [comment]
It works now, thank you very much!
