### ISSUE TITLE
Can a fingerprint sensor be used to unlock a gpg key?

### ISSUE THREAD

**Issue by marcSoda** [cruegge/pam-gnupg#40]
I have seen several posts insinuating that this application can be used to unlock a gpg key at login, but with no mention on how to do it. Is this possible? If so, how? On login I use pam_gnupg to unlock my gpg key with my password, but I would like to use the fingerprint sensor to do the same thing.

**Comment by cruegge** [comment]
That's not possible. All pam-gnupg does is to send your login password to gpg to unlock your keys. If you never enter your password, there's no way to make it work.
