### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by j1g5awi** [cruegge/pam-gnupg#41]
Hi, I install pam-gnupg and I follow steps in README:

- add `auth ... session ...` to /etc/pam.d/system-local-login
- add `allow-preset-passphrase` to ~/.gnupg/gpg-agent.conf
- add my keygrip to ~/.pam-gnupg

My system is Arch Linux, and my gpg passphrase is the same as password of user.

I have tried many solution in issues but doesn't work as before.

I set the debug option and reboot, but can't not see any log about it, sounds like it **never be loaded**.
I try to add `auth ... session ...` to /etc/pam.d/sudo, and I see log.
And I try to use command below to verify whether my passphrase is work, and it's right.

```
echo mypassphrase | /usr/lib/gnupg/gpg-preset-passphrase --preset mykeygrip
```

Is there anything wrong with me ?

**Comment by cruegge** [comment]
What display manager are you using? Can you post the corresponding file in `/etc/pam.d`?

**Comment by j1g5awi** [comment]
I use SDDM, and here is my file:

sddm-autologin

```
 #%PAM-1.0
auth        required    pam_env.so
auth        required    pam_faillock.so preauth
auth        required    pam_shells.so
auth        required    pam_nologin.so
auth        required    pam_permit.so
auth       optional    pam_gnome_keyring.so
-auth       optional    pam_kwallet5.so
account     include     system-local-login
password    include     system-local-login
session     include     system-local-login
session    optional    pam_gnome_keyring.so auto_start
session    optional    pam_kwallet5.so auto_start
```

system-local-login

```
#%PAM-1.0
auth      include   system-login
account   include   system-login
password  include   system-login
session   include   system-login
auth     optional  pam_gnupg.so store-only
session  optional  pam_gnupg.so
```

**Comment by cruegge** [comment]
Judging by the file name, you use autologin? In that case pam-gnupg can't work, if you never type in the password, there's nothing to send to the agent. Also, `sddm-autologin` does not include `system-local-login` during `auth`, explaining why there are no debug lines in the log.

**Comment by j1g5awi** [comment]
On 22/05/01 04:02上午, Chris Ruegge wrote:
> Judging by the file name, you use autologin? In that case pam-gnupg can't work, if you never type in the password, there's nothing to send to the agent. Also, `sddm-autologin` does not include `system-local-login` during `auth`, explaining why there are no debug lines in the log.
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/cruegge/pam-gnupg/issues/41#issuecomment-1114202291
> You are receiving this because you authored the thread.
> 
> Message ID: ***@***.***>

Oh, Looks like I just write the wrong file, when I write it to sddm, it works.

Thanks a lot !
