### ISSUE TITLE
How to make `GNUPGHOME` available to pam?

### ISSUE THREAD

**Issue by FF-AntiK** [cruegge/pam-gnupg#42]
The `README.md` says:

> To set it, add the path to the config file on a separate line before any keygrips, either as absolute path or starting with ~/ for paths relative to the home directory.

Which config file does the instruction intend?

**Comment by cruegge** [comment]
It refers to the same file you write the keygrips to, i.e. `~/.pam-gnupg` or `$XDG_CONFIG_HOME/pam-gnupg`.

**Comment by FF-AntiK** [comment]
Ah okay, I finally see where my confusion comes from. =D
So in `pam-gnupg` I just insert a line with the path to my GNUPGHOME before the keygrips?

Is it
```
~/.local/share/gnupg
```

or something like
```
GNUPGHOME=~/.local/share/gnupg
```
?

Thank you very much for your quick response!

**Comment by cruegge** [comment]
Ok, maybe I just expand the README paragraph a bit to be more explicit. It's only the path itself, without `GNUPGHOME=`.
