### ISSUE TITLE
Can pam-gnupg work with multiple login sessions?

### ISSUE THREAD

**Issue by amano-kenji** [cruegge/pam-gnupg#43]
There are 7 TTYs on linux.

**Comment by cruegge** [comment]
GPG uses only a single agent shared between all login sessions, so multiple sessions should work without issues.

**Comment by amano-kenji** [comment]
But, if one of loggined sessions logs out, what happens to the other sessions?

**Comment by cruegge** [comment]
pam-gnupg is really quite simple, it only send the input password to the agent. The depends on how the agent is started and how it's lifecycle is managed. pam-gnupg can optionally start the agent, but what happens after that depends on the system configuration. Maybe it's launched into the systemd user session and gets killed when the session terminates, but maybe not. Also, I think it's generally better to start the agent first as a systemd user service instead, and then the lifetime depends on that service's configuration. pam-gnupg simply does not handle these details at all.

**Comment by amano-kenji** [comment]
I don't use systemd.

**Comment by cruegge** [comment]
Well, then it depends on whatever service manager or session setup you're using.
