### ISSUE TITLE
missing PAM headers

### ISSUE THREAD

**Issue by azinsharaf** [cruegge/pam-gnupg#48]
hi, how can i install this missing package? I am on ubuntu 22.04 LTS. 
`configure: error: you are missing PAM headers`

**Comment by cruegge** [comment]
I'm not on Ubuntu, so can't check, but it's probably the [libpam0g-dev package](https://packages.ubuntu.com/jammy/libpam0g-dev).

**Comment by azinsharaf** [comment]
yep! thank you!
