### ISSUE TITLE
gpg keeps asking for password after setup

### ISSUE THREAD

**Issue by deadpyxel** [cruegge/pam-gnupg#6]
I've just followed the instructions to setup the GPG unlock for my mutt mail synchronization.

The lines about `auth` and `session` have been added to my `/etc/pam.d/lightdm`, and I have created a `~/.gnupg/gpg-agent.conf` with the `allow-preset-passphase` statement, but still every time I attempt to do anything that is gpg unlock related, the password is asked.

Maybe I messed up something in the setup, so please, tell me which files I need to look at and paste here so we can find what's wrong.

**Comment by deadpyxel** [comment]
I was using different passwords for my encryption key and user account, editing it has fixed it. Closing this.

**Comment by vitaliy-kuzmich** [comment]
hmm, @deadpyxel do you want to say that you have equal passwords to your system login, ssh, mail account, gpg account ? :)

**Comment by deadpyxel** [comment]
no, I mean I was using different system password and GPG password. As far as I understand, you need to have both system and gpg password equal for it to work properly. Please correct me if I am wrong @cruegge .

**Comment by cruegge** [comment]
No, you're right;  the login and gpg passphrase need to be the same, but all others can (and should...) be different.
