### ISSUE TITLE
After some time it starts to ask for password

### ISSUE THREAD

**Issue by deadpyxel** [cruegge/pam-gnupg#8]
## Description

While the automatic unlocking still works after login, after around 1 hour, the keyring starts to ask for password unlock. I am using this to automatically unlock my encrypted password for `mailsync`,setup with [mutt-wizard](https://github.com/LukeSmithxyz/mutt-wizard). This software was recommended by Luke in his documentation, but I don't think there's any specifics about the setup needed.

## Expected Behavior

The unlock should persist after login until logout.

## Actual Behavior

After 1 hour or so (need to time it), the GPG keyring starts to ask for the unlock password. 

## Steps to Reproduce

1. Setup given the instruction on `README`
2. Log in
3. After some time, the GPG keyring asks for password

## Context

My `mailsync` runs every 15 minutes, so while it should automatically unlock my encrypted password, it asks me for it every 15 minutes after around one hour working perfectly.

## Your Environment

* Version used: Latest AUR version
* Environment name and version: GPG 2.2.17, libgcrypt 1.8.5
* Operating System and version: Archlinux kernel 5.3.7-arch1-1-ARCH

**Comment by cruegge** [comment]
Did you set `max-cache-ttl` in your `gpg-agent.conf`?

**Comment by deadpyxel** [comment]
I did not. What would that require? Is it syntax specific?

**Comment by cruegge** [comment]
Just add a line like

~~~
max-cache-ttl 86400
~~~

to set the timeout to 1 day. I briefly mentioned that in the README, but maybe I'll expand that part a bit with an example.

**Comment by deadpyxel** [comment]
I added this. Should I reboot for testing the change?

I'll see the results and get back to you, but I believe this fix it.

**Comment by deadpyxel** [comment]
That did the trick. Thanks a lot for the explanation.
